# Generated by Django 5.2 on 2025-04-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('cadenceType', models.CharField(max_length=5)),
                ('cadenceAmount', models.IntegerField()),
                ('last_completion_datetime', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
