# Generated by Django 5.2 on 2025-04-06 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remember_me', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cadenceAmount',
            new_name='cadence_amount',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='cadenceType',
            new_name='cadence_type',
        ),
    ]
